apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configmap
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: application
    repoURL: https://github.com/gguldong/argocd-helm.git
    targetRevision: HEAD
